### PR TITLE
Fix gcc build

### PR DESCRIPTION
**Pull request by Mic92**
test with gcc 12

### CODE REVIEW

**Comment by Mic92** [comment]
friendly ping.

**Comment by Xuanwo** [comment]
Hi, thank you @Mic92 for your PR! This repo doesn't yet have CI coverage. I'll set up some basic CI and then merge your PR. Apologies for the delay.

**Comment by Xuanwo** [comment]
cc @PragmaTwice, would you like to take a review first?

**Comment by Mic92** [comment]
Feel free to apply this patch to your liking. I no longer need it.

**Comment by Xuanwo** [comment]
> Feel free to apply this patch to your liking. I no longer need it.

Got it. Thank you for your contribution.

**Pull request closed without merging**
